/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutCLoad: typeof import('./components/AboutCLoad.vue')['default']
    Chart: typeof import('./components/Chart.vue')['default']
    ChartOptions: typeof import('./components/ChartOptions.vue')['default']
    DropDownMenu: typeof import('./components/DropDownMenu.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    LogComponent: typeof import('./components/LogComponent.vue')['default']
    LogFileSearch: typeof import('./components/LogFileSearch.vue')['default']
    ProjectDescription: typeof import('./components/ProjectDescription.vue')['default']
    ProjectOverview: typeof import('./components/ProjectOverview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
    Weather: typeof import('./components/Weather.vue')['default']
    WeatherTest: typeof import('./components/WeatherTest.vue')['default']
  }
}
